# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/rss-helper',
                'doc_host': 'https://greenbes.github.io',
                'git_url': 'https://github.com/greenbes/rss-helper',
                'lib_path': 'rss_helper'},
  'syms': {'rss_helper.core': {'rss_helper.core.foo': ('rs_helper.html#foo', 'rss_helper/core.py')}}}
